[general_print_settings]
meta: BRLMQLPrintSettings
keys:
  BRLMQLPrintSettingsLabelSize
 # BRLMQLPrintSettingsLabelType
  BRLMPrintSettingsAutoCutForEachPageCount
  BRLMPrintSettingsAutoCut
  BRLMPrintSettingsCutAtEnd
  BRLMPrintSettingsResolution
  BRLMQLPrintSettingsBiColorRedEnhancement
  BRLMQLPrintSettingsBiColorGreenEnhancement
  BRLMQLPrintSettingsBiColorBlueEnhancement
  BRLMPrintSettingsFeedDirectionMargins
