[general_print_settings]
meta: BRLMPTPrintSettings
keys:
  BRLMPTPrintSettingsLabelSize
 # BRLMPTPrintSettingsLabelType
  BRLMPrintSettingsCutmarkPrint
  BRLMPTPrintSettingsCutPause
  BRLMPrintSettingsAutoCut
  # BRLMPrintSettingsMirrorPrint
  BRLMPrintSettingsHalfCut
  BRLMPrintSettingsChainPrint
  BRLMPrintSettingsSpecialTapePrint
  BRLMPrintSettingsResolution
  BRLMPrintSettingsAutoCutForEachPageCount
  BRLMPrintSettingsForceVanishingMargin
  BRLMPrintSettingsFeedDirectionMargins
