[general_print_settings]
meta: BRLMPJPrintSettings
keys:
  BRLMPJPrintSettingsPaperSize
  BRLMPJPrintSettingsPaperType
  BRLMPJPrintSettingsPaperInsertionPosition
  BRLMPJPrintSettingsFeedMode
  BRLMPJPrintSettingsExtraFeedDots
  BRLMPJPrintSettingsDensity
  # BRLMPrintSettingsLengthScale
  BRLMPJPrintSettingsRollCase
  BRLMPJPrintSettingsPrintSpeed
  BRLMPrintSettingsUsingCarbonCopyPaper
  BRLMPrintSettingsPrintDashLine
  BRLMPJPrintSettingsForceStretchPrintableArea
  
