[general_print_settings]
meta: BRLMTDPrintSettings
keys:
  BRLMCustomPaperSize
  # BRLMPrintSettingPaperTypeTD
  # BRLMPJPrintSettingsFeedMode
  BRLMTDPrintSettingsDensity
  BRLMPrintSettingsPeelLabel
  BRLMPrintSettingsAutoCut
  BRLMPrintSettingsCutAtEnd
  BRLMPrintSettingsAutoCutForEachPageCount
  BRLMPrintSettingsFeedDirectionMargins
  BRLMPrintSettingsCustomRecord