[general_print_settings]
meta: BRLMRJPrintSettings
keys:
  BRLMCustomPaperSize
  # BRLMRJPrintSettingsPaperType
  # BRLMPJPrintSettingsFeedMode
  BRLMRJPrintSettingsDensity
  BRLMPrintSettingsRotate180degrees
  BRLMPrintSettingsPeelLabel
  BRLMPrintSettingsFeedDirectionMargins
