[general_print_settings]
meta: GeneralPrintSettings
keys:
  BRLMPTPrintSettingsLabelSize
  BRLMQLPrintSettingsLabelSize
  BRLMPrinterModel
  BRLMChannelType
  BRLMPrintSettingsScaleMode
  BRLMPrintSettingsScaleValue
  BRLMPrintSettingsOrientation
  BRLMPrintSettingsRotation
  BRLMPrintSettingsHalftone
 # BRLMPTPrintSettingsLabelType
 # BRLMQLPrintSettingsLabelType
  BRLMPrintSettingsHorizontalAlignment
  BRLMPrintSettingsVerticalAlignment
  BRLMPrintSettingsCompressMode
  BRLMPrintSettingsForceVanishingMargin
  BRLMPrintSettingsHalftoneThreshold
  BRLMPrintSettingsNumCopies
  BRLMPrintSettingsAutoCutForEachPageCount
  BRLMPrintSettingsAutoCut
  BRLMPrintSettingsCutAtEnd
  # BRLMPrintSettingsTwoColorPrint
  BRLMPrintSettingsCutmarkPrint
  BRLMPrintSettingsMirrorPrint
  BRLMPrintSettingsHalfCut
  BRLMPrintSettingsChainPrint
  BRLMPrintSettingsSpecialTapePrint
  BRLMPJPrintSettingsPaperSize
  BRLMPJPrintSettingsPaperType
  BRLMPJPrintSettingsPaperInsertionPosition
  BRLMPJPrintSettingsFeedMode
  BRLMPJPrintSettingsExtraFeedDots
  BRLMPJPrintSettingsDensity
  # BRLMPrintSettingsLengthScale
  BRLMPJPrintSettingsRollCase
  BRLMPJPrintSettingsPrintSpeed
  BRLMPrintSettingsUsingCarbonCopyPaper
  BRLMPrintSettingsPrintDashLine
  BRLMPJPrintSettingsForceStretchPrintableArea
  BRLMCustomPaperSize
  # BRLMRJPrintSettingsPaperType
  # BRLMPJPrintSettingsFeedMode
  BRLMRJPrintSettingsDensity
  BRLMPrintSettingsRotate180degrees
  BRLMPrintSettingsPeelLabel
  BRLMTDPrintSettingsDensity
  BRLMMWPrintSettingsPaperSize
  BRLMPrintSettingsSkipStatusCheck
  BRLMPrintSettingsPrintQuality
  BRLMPrintSettingsResolution
  BRLMPTPrintSettingsCutPause
  BRLMQLPrintSettingsBiColorRedEnhancement
  BRLMQLPrintSettingsBiColorGreenEnhancement
  BRLMQLPrintSettingsBiColorBlueEnhancement
  BRLMPrintSettingsCustomRecord
  BRLMPrintSettingsTrimTrailingBlankData
  BRLMPrintSettingsFeedDirectionMargins