[PrinterConfig]
meta: PrinterConfigGet
keys:
    AutoPowerOffTime
    BluetoothAutoReconnection
    BluetoothDeviceName
    BluetoothDiscoverable
    BluetoothFunctionalityActivationOnPowerUp
    IPv4AddressAssignmentMethod
    IPv4DefaultGateway
    IPv4DNSResolutionMethod
    IPv4PrimaryDNSAddress
    IPv4SecondaryDNSAddress
    IPv4StaticAddress
    IPv4SubnetMask
    IPv6AddressList
    IPv6AddressPriority
    IPv6Availability
    IPv6EnableStaticAddress
    IPv6PrimaryDNSAddress
    IPv6SecondaryDNSAddress
    IPv6StaticAddress
    JpegPrintAutoScaling
    JpegPrintHalftoneStyle
    NetworkFunctionalityActivationOnPowerUp
    NetworkInterfaceMode
    NetworkNodeName
    PrintDensity
    PrintSpeed
    PrintSpeedPJ
    WiFiAuthenticationMode
    WiFiChannel
    WiFiConnectionMode
    WiFiEncryptionMode
#    WiFiWPAPassphrase
#    WiFiEAPPassword
    WiFiSSID
#    WiFiEAPUserID
#    WiFiWEPKey
    WirelessDirectKeyGenerationMethod
#    WirelessDirectStaticNetworkKey
    WirelessDirectStaticSSID
