[media]
key: MediaBackgroundColor
# type( enum, int, float, bool, string )
type: enum
values:
  Standard
  White
  Others
  Clear
  Red
  Blue
  Yellow
  Green
  Black
  ClearWithWhiteInk
  PremiumGold
  PremiumSilver
  PremiumOthers
  MaskingOthers
  MatteWhite
  MatteClear
  MatteSilver
  SatinGold
  SatinSilver
  PastelPurple
  BlueWithWhiteInk
  RedWithWhiteInk
  FluorescentOrange
  FluorescentYellow
  BerryPink
  LightGray
  LimeGreen
  SatinNavyBlue
  SatinWineRed
  FabricYellow
  FabricPink
  FabricBlue
  TubeWhite
  SelfLaminatedWhite
  FlexibleWhite
  FlexibleYellow
  CleaningWhite
  StencilWhite
  LightBlue_Satin
  Mint_Satin
  Silver_Satin
  Incompatible
