[media]
key: MediaType
# type( enum, int, float, bool, string )
type: enum
values:
  L3.5mm
  L6mm
  L9mm
  L12mm
  L18mm
  L24mm
  L29mm
  L36mm
  L38mm
  L50mm
  L54mm
  L62mm
  L102mm
  L103mm
  L17mmx54mm
  L17mmx87mm
  L23mmx23mm
  L29mmx42mm
  L29mmx90mm
  L38mmx90mm
  L39mmx48mm
  L52mmx29mm
  L54mmx29mm
  L60mmx86mm
  L62mmx29mm
  L62mmx60mm
  L62mmx75mm
  L62mmx100mm
  L102mmx51mm
  L102mmx152mm
  L103mmx164mm
  L12mmDia
  L24mmDia
  L58mmDia
  HS5.8mm
  HS8.8mm
  HS11.7mm
  HS17.7mm
  HS23.6mm
  HS5.2mm
  HS9.0mm
  HS11.2mm
  HS21.0mm
  HS31.0mm
  FL21mmx45mm
  A4
  A5
  A5_Landscape
  Letter
  Legal
  Custom
