[media]
key: MediaTextColor
# type( enum, int, float, bool, string )
type: enum
values:
  Standard
  White
  Others
  Red
  Blue
  Black
  Gold
  RedAndBlack
  FabricBlue
  CleaningBlack
  StencilBlack
  Incompatible