[media]
key: MediaPJRollCase
exif: rollCasePJ
# default
exif2: None
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    None
    PARC001_NoAntiCurl
    PARC001
    PARC001_ShortFeed
    KeepPrinterSetting
