[model_spec_legacy]
# 印字指令の際のページ指定コマンドの種類
key: ModelSpecLegacyPrintPageCommandType
exif: page_command_mode_
# type( enum, int, float, bool, string )
type: enum
values:
    PAGE_START_END
    PAGE_START_NEXT_END