[model_spec_legacy]
# バッテリ取得方法
key: ModelSpecLegacyBatteryCommandType
exif: battery_
# type( enum, int, float, bool, string )
type: enum
values:
    # バッテリなし、非対応
	PS_BAT_NON
    # PJ用のバッテリ取得コマンドを使用
    PS_BAT_PJCOMMAND
    # MW145用のバッテリ取得コマンドを使用
    PS_BAT_MW145COMMAND
    # MW260用のバッテリ取得コマンドを使用
    PS_BAT_MW260COMMAND
    # ステータスから取得
    PS_BAT_FROMSTATUS