[model_spec_legacy]
# Networkの設定できる項目
key: ModelSpecLegacyPrinterSettingCategoryNetwork
exif: support_net_settings_
# type( enum, int, float, bool, string )
type: enum
values:
# Networkの設定できる項目 PSNetSetting
    # IPv6を有効にするか
    PS_NET_IPV6
    # 無線でIPv6に対応するか
    PS_WIFI_IPV6
    # 起動設定が可能かどうか
    PS_WIFI_BOOTMODE
    # Wireless DirectとWiFiの選択肢があるか？
    PS_WIFI_INTERFACE
    # WIFIとWireless Directを同時にONにできるか？
    PS_WIFI_WIRELESSDIRECT_BOOTMODE
    # Wifiの全体の設定
    PS_WIFI_SETTINGS
    # ノード名を設定できるかどうか
    PS_WIFI_NODENAME
    # LANの全体の設定
    PS_LAN_SETTINGS
    # ノード名を設定できるかどうか
    PS_LAN_NODENAME
    PS_LAN_IPV6
    # バイス接続方法の設定(0:Manual, 1:OnePush, 2:PIN)を選択可能にするかどうか
    PS_WIRELESSDIRECT_CREATE_KRY
    PS_WIRELESSDIRECT_SETTINGS