[model_spec_legacy]
# Networkの設定できる項目
key: ModelSpecLegacyPrinterSettingCategoryPower
exif: support_power_settings_
# type( enum, int, float, bool, string )
type: enum
values:
# パワーオン時間の設定 PSPowerSetting
    PS_POWER_POWEROFFTIME
    PS_POWER_POWEROFFTIME_BATTERY
    # 10秒単位と1秒単位でセットするコマンドを個別に投げる(PS_POWER_POWEROFFTIMEの拡張版)
    PS_POWER_POWEROFFTIME_RJ2
    # 10分単位と1分単位でセットするコマンドを個別に投げる(PS_POWER_POWEROFFTIMEの拡張版)
    PS_POWER_POWEROFFTIME_QL8
    PS_POWER_POWEROFFTIME_BATTERY_QL8
    PS_POWER_POWEROFFTIME_QL1100
    # RJ2の拡張
    PS_POWER_POWEROFFTIME_RJ4000a
    # BATTERY駆動時にRJ4000aのAC駆動時と同等のコマンドを使う
    PS_POWER_POWEROFFTIME_BATTERY_PJ8
    # モデルのFilter
    PS_POWER_POWEROFFTIME_ModelFilter
    # 電源のFilter
    PS_POWER_POWEROFFTIME_PowerSupplyFilter