[model_spec_legacy]
# 終端コード設定 ページ終わりのコマンド種類
key: ModelSpecLegacyPageEndCommandType
exif: end_command_
# type( enum, int, float, bool, string )
type: enum
values:
	# PJ向けのコマンドを使用
    END_PJCODE
    END_NORMAL