[model_spec_legacy]
# プリンタが対応している機能
key: ModelSpecLegacySupportFunc
exif: support_fun_
# type( enum, int, float, bool, string )
type: enum
values:
    # ラスタ印刷に対応
    SP_FUC_RASTER_PRINT
    # テンプレート印刷に対応
    SP_FUC_TEMPLATE_PRINT
    # テンプレート転送に対応
    SP_FUC_TEMPLATE_TRANS
    # テンプレート削除機能に対応
    SP_FUC_TEMPLATE_REMOVE
    # 設定機能に対応する
    SP_FUC_PRINTER_SETTINGS
    # ファームアップデートに対応する
    SP_FUC_FIRM_UPDATE