[model_spec_legacy]
# ファームバージョン取得コマンドの種類
key: ModelSpecLegacyMainVersionCommandType
exif: firm_version_kind_
# type( enum, int, float, bool, string )
type: enum
values:
	# PJ,RJ-3向け
    MV_U0FH01H01H
    # MW向け
    MV_U0EH01H
    # RJ-4
    MV_U0FH02H01H
    # 不明
    MV_UNKWOUN