[model_capability]
key: ModelCapabilityAutoCutSettingPriorityWhenEveryTrueLastFalse
# type( enum, int, float, bool, string )
type: enum
values:
  PrioritizeAutoCutEveryTrue
  PrioritizeAutoCutLastFalse