[model_spec_legacy]
# Networkの設定できる項目
key: ModelSpecLegacyPrinterSettingCategoryPrint
exif: support_print_settings_
# type( enum, int, float, bool, string )
type: enum
values:
# 本体設定できる項目 PSPrintSetting
    PS_PRINT_JPEG_HALFTONE
    PS_PRINT_JPEG_SCALE
    PS_PRINT_DENSITY
    PS_PRINT_SPEED
    PS_PRINT_CUTPAUSE_TIME
