[model_spec_legacy]
# how to feed paper (only for PocketJet)
key: ModelSpecLegacySupportPJFeedMode
exif: support_pjfeed_
# type( enum, int, float, bool, string )
type: enum
values:
	# There is no paper feed at the end of a job. Use this with non-perforated roll paper to save paper.
    FEED_MODE_FREE
    # The paper always feeds at the end of a job to complete the vertical page size specified. Use this with cut sheet paper.
    FEED_MODE_FIXEDPAGE
    # The printer feeds paper until an "out-of-paper" condition is found. Use this with perforated paper.
    FEED_MODE_ENDOFPAGE
    # For the marked roll paper, the printer adjusts the first position of the paper after feeding paper until the end of the page is detected.(only for PJ-600 series)
    FEED_MODE_ENDOFPAGERETRACT