[model_spec_legacy]
# 用紙一覧の種別
key: ModelSpecLegacyPaperListKind
exif: paper_kind_
# type( enum, int, float, bool, string )
type: enum
values:
    PS_A7
    PS_A6
    PS_PJ
    PS_BIN
    PS_QL
    PS_PT
    PS_PT_36mm
    PS_PT_18mm
    PS_TUBE
    PS_FLE
    PS_PT3
    PS_QL1000
    PS_PT_CUBE3
    PS_PT9000
    PS_PT_3_5mmUNSUPPORT
    PS_PT_HS3
    PS_PT_36mm_HS3
    PS_PT_24mmUNSUPPORT
    PS_PT_HS3_24mmUNSUPPORT
    PAPER_UNSUPPORT
