[model_spec_legacy]
# グラフィックコマンドの種別
key: ModelSpecLegacyGraphicCommandType
exif: g_command_
# type( enum, int, float, bool, string )
type: enum
values:
    G_COMMAND_g
    G_COMMAND_G
    G_COMMAND_PJ