[model_spec_legacy]
# ラベルカラーの情報
# ラベルやインク色を取得する
key: ModelSpecLegacySupportMultiColorLabel
exif: is_colorlabel_
# type( enum, int, float, bool, string )
type: enum
values:
    MONO_COLOR
    BI_COLOR
    UNSUPPORTED_COLOR