[model_spec_legacy]
# Networkの設定できる項目
key: ModelSpecLegacyPrinterSettingCategory
exif: support_net_settings_
# type( enum, int, float, bool, string )
type: enum
values:
# Networkの設定できる項目 PSNetSetting
    # IPv6を有効にするか
    PS_NET_IPV6
    # 無線でIPv6に対応するか
    PS_WIFI_IPV6
    # 起動設定が可能かどうか
    PS_WIFI_BOOTMODE
    # Wireless DirectとWiFiの選択肢があるか？
    PS_WIFI_INTERFACE
    # WIFIとWireless Directを同時にONにできるか？
    PS_WIFI_WIRELESSDIRECT_BOOTMODE
    # Wifiの全体の設定
    PS_WIFI_SETTINGS
    # ノード名を設定できるかどうか
    PS_WIFI_NODENAME
    # LANの全体の設定
    PS_LAN_SETTINGS
    # ノード名を設定できるかどうか
    PS_LAN_NODENAME
    PS_LAN_IPV6
    # バイス接続方法の設定(0:Manual, 1:OnePush, 2:PIN)を選択可能にするかどうか
    PS_WIRELESSDIRECT_CREATE_KRY
    PS_WIRELESSDIRECT_SETTINGS
# Bluetoothの設定できる項目 PSBluetoothSetting
    # オートパワーオフ時間を設定できるかどうか
    PS_BT_AUTOPOWEROFFTIME
    PS_BT_AUTOSLEEPTIME
    PS_BT_AUTOSLEEPTOPOWEROFFTIME
    PS_BT_POWERSAVEMODE
    # 他のデバイスから検索できるかどうか
    PS_BT_ISDISCOVERABLE
    # デバイス名
    PS_BT_DEVICENAME
    # PINCode
    PS_BT_PINCODE
    PS_BT_SSP
    # PINCodeの有効無効設定が可能かどうか
    PS_BT_PINCODE_ENABLE
    PS_BT_SECURITYMODE
    PS_BT_BOOTMODE
    PS_BT_BLUETOOTH_TO_IRDA
    PS_BT_BLUETOOTH_TO_NET
    # ペアリング時に本体キー操作を要求する
    PS_BT_KEY
    PS_BT_AUTO_CONNECTION
	# BOOT設定のコマンドをPJと同じコマンドにする
    PS_BT_BOOTMODE_PJ
# 本体設定できる項目 PSPrintSetting
    PS_PRINT_JPEG_HALFTONE
    PS_PRINT_JPEG_SCALE
    PS_PRINT_DENSITY
    PS_PRINT_SPEED
    PS_PRINT_CUTPAUSE_TIME
# パワーオン時間の設定 PSPowerSetting
    PS_POWER_POWEROFFTIME
    PS_POWER_POWEROFFTIME_BATTERY
    # 10秒単位と1秒単位でセットするコマンドを個別に投げる(PS_POWER_POWEROFFTIMEの拡張版)
    PS_POWER_POWEROFFTIME_RJ2
    # 10分単位と1分単位でセットするコマンドを個別に投げる(PS_POWER_POWEROFFTIMEの拡張版)
    PS_POWER_POWEROFFTIME_QL8
    PS_POWER_POWEROFFTIME_BATTERY_QL8
    PS_POWER_POWEROFFTIME_QL1100
    # RJ2の拡張
    PS_POWER_POWEROFFTIME_RJ4000a
    # モデルのFilter
    PS_POWER_POWEROFFTIME_ModelFilter
    # 電源のFilter
    PS_POWER_POWEROFFTIME_PowerSupplyFilter
