[model_spec_legacy]
# 対応している拡張コマンドの種類
key: ModelSpecLegacySupportAdvanceModeCommand
exif: support_advanced_mode_
# type( enum, int, float, bool, string )
type: enum
values:
    # ハーフカット設定
    PS_AM_HALFCUT
    # PS_AM_NO_CHAIN = 0x02,/**< @brief 連続印刷のとき最後の1枚を印刷後フィード*/

	# 連続印刷のとき最後の1枚を印刷後フィードカットする
	PS_AM_CUTEND
	# 特殊テープ（カットなし）
	PS_AM_SPECIALTAPE
	# 高精細印刷
	PS_AM_HIGH_RESOLUTION
	# 連続印刷のとき最後の１枚の後部をカットします。 1：ラベル後部カットする 0：ラベル後部カットしない
	PS_AM_LABEL_CUTEND
	PS_AM_NOBUFFER
	# ドラフト印刷
	PS_AM_LOW_RESOLUTION