[model_spec_legacy]
# 対応している各種設定コマンドの種類
key: ModelSpecLegacySupportVariousModeCommand
exif: support_various_mode_
# type( enum, int, float, bool, string )
type: enum
values:
    PS_VM_AUTOCUT
    PS_VM_MIRROR
    PS_VM_PEEL
    PS_VM_ROTATE180
    PS_VM_CUTMARK
    PS_FEEDVOL