[model_spec_legacy]
# 圧縮モード mode9は別Flagになっている supported_tiff_mode_
key: ModelSpecLegacyPrintCompressType
exif: supported_tiff_mode_
# type( enum, int, float, bool, string )
type: enum
values:
	# 非圧縮のみ
    COM_RAW
    # 非圧縮/TIFF圧縮に対応
    COM_RAW_TIFF
    # TIFF圧縮のみ
    COM_TIFF