[model_spec_legacy]
# Networkの設定できる項目
key: ModelSpecLegacyPrinterSettingCategoryBluetooth
exif: support_bluetooth_settings_
# type( enum, int, float, bool, string )
type: enum
values:
# Bluetoothの設定できる項目 PSBluetoothSetting
    # オートパワーオフ時間を設定できるかどうか
    PS_BT_AUTOPOWEROFFTIME
    PS_BT_AUTOSLEEPTIME
    PS_BT_AUTOSLEEPTOPOWEROFFTIME
    PS_BT_POWERSAVEMODE
    # 他のデバイスから検索できるかどうか
    PS_BT_ISDISCOVERABLE
    # デバイス名
    PS_BT_DEVICENAME
    # PINCode
    PS_BT_PINCODE
    PS_BT_SSP
    # PINCodeの有効無効設定が可能かどうか
    PS_BT_PINCODE_ENABLE
    PS_BT_SECURITYMODE
    PS_BT_BOOTMODE
    PS_BT_BLUETOOTH_TO_IRDA
    PS_BT_BLUETOOTH_TO_NET
    # ペアリング時に本体キー操作を要求する
    PS_BT_KEY
    PS_BT_AUTO_CONNECTION
	# BOOT設定のコマンドをPJと同じコマンドにする
    PS_BT_BOOTMODE_PJ