[model_spec_legacy]
# ファームアップデート時のモード切替コマンドが必要 changed_update_firm_mode_
key: ModelSpecLegacyFirmUpdateShouldChangeCommandMode
exif: changed_update_firm_mode_
# type( enum, int, float, bool, string )
type: bool