[print]
key: PrintQuality
# type( enum, int, float, bool, string )
type: enum
values:
	LowResolutionHighSpeed
    NormalResolutionNormalSpeed
    NormalResolutionDoubleSpeed
    HighResolutionLowSpeed
    HighResolutionUsingHRImageLowSpeed
