[BRLMPrinterDefine]
# ChannelType
key: BRLMChannelType
exif: channelType
# default
exif2: BluetoothMFi
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
#    USB
    BluetoothMFi
    WiFi
    BluetoothLowEnergy

