[NotUse]
key: BRLMRJPrintSettingsPaperType
exif: paperTypeRJ
# default
exif2: Roll
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Roll
    PerforatedRoll
    DieCutLabel
