[BRLMPJPrintSettingPaperSize]
# LabelSize
key: BRLMPJPrintSettingsPaperSize
exif: paperSizePJ
# default
exif2: [[BRLMPJPrintSettingsPaperSize alloc] initWithPaperSizeStandard:BRLMPJPrintSettingsPaperSizeStandardA4]
# type( enum, int, float, bool, string, object, struct )
type: object
