[BRLMPrinterConfig]
# TypeName
key: IPv4AddressAssignmentMethod
# argumentName
exif: iPv4AddressAssignmentMethod
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Auto
    DynamicHostConfigurationProtocol
    BootstrapProtocol
    ReverseAddressResolutionProtocol
    Static