[NotUse]
key: BRLMPTPrintSettingsLabelType
exif: labelTypePT
# default
exif2: Laminate
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    NoTape
    Laminate
    # TODO: check if needed
    Lettering
    NonLaminate
    Fabric
    Stamp
    # TODO: check if needed
    Microporous
    HeatShrink
    FLe
    FlexibleID
    Satin
    NoSupport
    HeatShrink_3_1