[BRLMPrintImageSettings]
key: BRLMPrintSettingsCompressMode
exif: compress
# default
exif2: Mode9
# TODO: check mode9 after RemoveWhiteSpace
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    None
    # TODO: check support models
    # PJ does not suuport
    Tiff
    # TODO: chack support models
    Mode9
