[BRLMPJPrintSettings]
key: BRLMPJPrintSettingsPaperInsertionPosition
exif: paperInsertionPositionPJ
# default
exif2: Left
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Left
    Center
    Right
