[BRLMPrinterConfig]
# TypeName
key: WirelessDirectKeyGenerationMethod
# argumentName
exif: wirelessDirectKeyGenerationMethod
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Static
    Auto