[BRLMPrintImageSettings]
key: BRLMPrintSettingsOrientation
exif: printOrientation
# default
exif2: Portrait
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Portrait
    # Landscape90
    # Portrait180
    Landscape
