[BRLMPrintImageSettings]
# LabelSize
key: BRLMPrintSettingsAutoCutForEachPageCount
exif: autoCutForEachPageCount
# default
exif2: 1
description:
 Description : Specify the page number in “cut each # labels”
 Range(#) : 1 - 255
 Default : 1
# type( enum, int, float, bool, string, object, struct, uint8 )
type: uint8
