[BRLMRJPrintSettings]
key: BRLMRJPrintSettingsDensity
exif: densityRJ
# default
exif2: UsePrinterSetting
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    WeakLevel5
    WeakLevel4
    WeakLevel3
    WeakLevel2
    WeakLevel1
    Neutral
    StrongLevel1
    StrongLevel2
    StrongLevel3
    StrongLevel4
    StrongLevel5
    UsePrinterSetting
