[BRLMQLPrintSettings]
key: BRLMQLPrintSettingsBiColorRedEnhancement
exif: biColorRedEnhancement
# default
exif2: 0
description:
 Range(#) : -20 - 20
# type( enum, int, float, bool, string, object, struct, uint8 )
type: int
