[BRLMPrintImageSettings]
key: BRLMPrintSettingsHalftone
exif: halftone
# default
exif2: Threshold
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Threshold
    ErrorDiffusion
    PatternDither
