[BRLMPrinterConfig]
# TypeName
key: PrintSpeedPJ
# argumentName
exif: printSpeedPJ
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    HighSpeed
    MediumHighSpeed
    MediumLowSpeed
    LowSpeed
    Fast_DraftQuality
    Fast_LineConversion