[BRLMPrinterConfig]
# TypeName
key: NetworkFunctionalityActivationOnPowerUp
# argumentName
exif: networkFunctionalityActivationOnPowerUp
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Enable
    Disable
    KeepLastState