[BRLMPJPrintSettings]
key: BRLMPJPrintSettingsFeedMode
exif: feedMode
# default
exif2: NoFeed
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    NoFeed
    FixedPage
    EndOfPage
    EndOfPageRetract
