[BRLMPrinterConfig]
# TypeName
key: JpegPrintHalftoneStyle
# argumentName
exif: jpegPrintHalftoneStyle
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    SimpleThreshold
    ErrorDiffusion