[BRLMPrintImageSettings]
key: BRLMPrintSettingsVerticalAlignment
exif: vAlignment
# default
exif2: Top
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Top
    Center
    Bottom
