[BRLMPrinterConfig]
# TypeName
key: BluetoothFunctionalityActivationOnPowerUp
# argumentName
exif: bluetoothFunctionalityActivationOnPowerUp
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Enable
    Disable
    KeepLastState