[BRLMPrinterConfig]
# TypeName
key: WiFiAuthenticationMode
# argumentName
exif: wiFiAuthenticationMode
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    OpenSystem
    SharedKey
    WPA__WPA2_PSK
    LEAP
    EAP_FAST__NONE
    EAP_FAST__MS_CHAPv2
    EAP_FAST__GTC
    PEAP__MS_CHAPv2
    PEAP__GTC
    EAP_TTLS__CHAP
    EAP_TTLS__MS_CHAP
    EAP_TTLS__MS_CHAPv2
    EAP_TTLS__PAP
    EAP_TLS
    WPA__WAP2_PSK__WPA3_SAE
    WPA3_SAE
    