[BRLMPTPrintSettings]
# LabelSize
key: BRLMPTPrintSettingsLabelSize
exif: labelSizePT
# default
exif2: Width6mm
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Width3_5mm
    Width6mm
    Width9mm
    Width12mm
    Width18mm
    Width24mm
    Width36mm
    WidthHS_5_8mm
    WidthHS_8_8mm
    WidthHS_11_7mm
    WidthHS_17_7mm
    WidthHS_23_6mm
    WidthFL_21x45mm
    WidthHS_5_2mm
    WidthHS_9_0mm
    WidthHS_11_2mm
    WidthHS_21_0mm
    WidthHS_31_0mm
