[BRLMPrintImageSettings]
key: BRLMPrintSettingsResolution
exif: resolution
# default
exif2: Normal
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Low
    Normal
    High