[BRLMPrintImageSettings]
key: BRLMPrintSettingsRotation
exif: imageRotation
# default
exif2: Rotate0
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Rotate0
    Rotate90
    Rotate180
    Rotate270
