[BRLMPrinterConfig]
# TypeName
key: IPv4DNSResolutionMethod
# argumentName
exif: iPv4DNSResolutionMethod
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Static
    Auto