[NotUse]
# LabelSize
key: BRLMPrintSettingsTwoColorPrint
exif: twoColorPrint
# default
exif2: NO
description:
 Model : QL-800/810W/820NWB
# type( enum, int, float, bool, string, object, struct, uint8 )
type: bool
