[BRLMPJPrintSettings]
key: BRLMPJPrintSettingsPrintSpeed
exif: printSpeedPJ
# default
exif2: HighSpeed
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
   HighSpeed
   MediumHighSpeed
   MediumLowSpeed
   LowSpeed
   Fast_DraftQuality
   Fast_LineConversion
   UsePrinterSetting
# deprecated
   2_5inchPerSec
   1_9inchPerSec
   1_6inchPerSec
   1_1inchPerSec
