[BRLMPrinterConfig]
# TypeName
key: PrintDensity
# argumentName
exif: printDensity
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    High5_Highest
    High4
    High3
    High2
    High1
    Medium
    Low1
    Low2
    Low3
    Low4
    Low5_Lowest