[NotUse]
key: BRLMQLPrintSettingsLabelType
exif: labelTypeQL
# default
exif2: Roll
description:
 not common
 FIXME: consider to separate
         PJPaperType / RJPaperType / ...
    BRPrintSettingPapertyperoll = 1, // unmarked roll, used by pj, rj, and td
    BRPrintSettingPapertypecutsheet, // pj only
    BRPrintSettingPapertypeperfroll, // marked roll, used by pj, rj, and td
    BRPrintSettingPapertypeperfrollretract, // marked roll, with forced retraction, used by pj only
    BRPrintSettingPapertypediecutlabel, // label, used by rj and td only
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    Roll
    CutSheet
    PerfRoll
    PerfRollRetract
    DieCutLabel
