[BRLMPrinterConfig]
# TypeName
key: WiFiEncryptionMode
# argumentName
exif: wiFiEncryptionMode
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    None
    WEP
    TKIP
    AES
    CKIP
    CMIC
    CKIP_CMIC
    TKIP_AES