[BRLMPrintImageSettings]
key: BRLMPrintSettingsScaleMode
exif: scaleMode
# default
exif2: FitPageAspect
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
    ActualSize
    # FitPage
    FitPageAspect
    # FitWidthAspectAutoHeight
    FitPaperAspect
    ScaleValue
