[BRLMPrinterConfig]
# TypeName
key: NetworkInterfaceMode
# argumentName
exif: networkInterfaceMode
# type( enum, int, float, bool, string, object, struct )
type: enum
values:
	Off
    WiFi
    WirelessDirect
    WiFiAndWirelessDirect