[print_settings]
meta: PrintSettings
keys:
# 用紙長さ ( strPaperName )
  MediaSize
# 画像印刷時の用紙の向き ( Orientation orientation_ )
  ImageOrientation
# 印刷モード ( nPrintMode )
  # PrintMode
# 画像印刷時の印刷モード ( ScaleMode scalemode_ )
  PrintScalingMode
# 画像印刷時の二値化の減色方法 ( HalftoneModthod halftone_, int16_t half_threshold_ )
  ImageHalftone
# 画像の明るさ ( int8_t image_brightness_ )
  ImageBrightness
# 画像のコントラスト ( int8_t image_contrast_ )
  ImageContrast
# 画像の赤色強調 ( int8_t image_red_enhancement_ )
  ImageRedEnhancement
# 画像の緑色強調 ( int8_t image_green_enhancement_ )
  ImageGreenEnhancement
# 画像の青色強調 ( int8_t image_blue_enhancement_ )
  ImageBlueEnhancement
# 画像印刷時の水平方向アライメント ( Align halign_ )
  PrintHorizontalAlign
# 画像印刷時の垂直方向アライメント ( VAlign valign_ )
  PrintVerticalAlign
# 画像印刷時の上余白 ( int32_t top_margin_ )
  PrintTopMargin
# 画像印刷時の左余白 ( int32_t left_margin_ )
  PrintLeftMargin
# メディアの文字のカラー
  MediaTextColor
# メディアの背景のカラー
  MediaBackgroundColor
# 印刷倍率 ( double scale_ )
  PrintScalingValue
# Mirror有効にするか ( bool is_mirror_ )
  # Mirror
# 180度回転指定 ( bool is_rotate180_ )
  # Rotate
# Endカットを有効にするか ( bool is_endcut_ )
  PrintAutoCutLast
# Autoカットを有効にするか ( bool is_autocut_ )
  PrintAutoCutEvery
# Auto cutを実行するページ単位 ( int16_t auto_cut_page_ )
  PrintAutoCutEveryCyclePerPage
# 特殊用紙設定を有効にするか ( bool is_specialtape_ )
  PrintAutoCutDisableForSpecialTape
# ハーフカットを有効にするか ( bool is_half_ )
  PrintAutoHalfCut
# 濃度の調整設定 ( int8_t density_ )
  PrintDensity
# 印刷速度 ( uint8_t speed_ )
  PrintSpeed
# ミシン目 ( bool is_dashLine_ )
  PrintDashLine
# 複写紙使用 */       /* bool is_carbon_
  PrintUsingCarbonCopyPaper
# 暗号化を有効にする ( bool is_aes_ )
# PJのフィード動作 ( PJFeedMode pj_feed_ )
  PrintFeedMode
# ハクリモード指定 ( bool is_peel_ )
  # Peel
# モード9を使用するかどうか ( bool mode9_ )
  # Mode9
# カットマークの印刷 ( bool is_cutmark_ )
  # CutMark
# 余白設定 ( int32_t label_margin_ )
  # LabelMargin
# ラベル後部カット ( bool is_label_endcut_ )
  # LabelEndCut
# 印字品質 ( uint8_t print_quality_ )
  PrintQuality
# ロールプリンターケース ( PJRollCase roll_case_mode_ )
  MediaPJRollCase
# 給紙位置 ( Align paper_position_ )
  MediaPaperInsertionPosition
# PJ用紙種類
  MediaPJPaperType
# 印刷後にステータス確認を行うかどうか ( CheckPrintEnd check_print_end_ )
  # CheckPrintEnd
# カスタムペーパー情報のPath ( std::string custompaper_path_ )
  # CheckPrintEnd
# width of custom paper(only for pocketjet) ( int32_t custom_width_ )
# length of custom paper(only for pocketjet) ( int32_t custom_length_ )
  MediaPJCustomSize
  MediaPJForceStretchPrintableArea
# length of feeding paper after printing (only for pocketjet) ( int32_t custom_feed_ )
  PrintExtraFeedDots
# コピー印刷数 ( int32_t numberofcopies_ )
  PrintCopies
# 印刷前のスキップ動作 ( bool bidirectional_ )
  PrintBidirectionalCommunication
# ファイルの保存先 ( std::string save_file_ )
  # PrintSaveFilePath
# 保存ファイルを上書きする ( bool overwrite_ )
  # Overwrite
# 使用するPaperクラス。直接指定しても良い。指定されていない場合はpaper_id__またはcustompaper_path_から作られる ( Paper paper_ )
  # Paper
# 後部余白カット ( bool trim_tape_after_data_ )
  ImageTrimBlankDataFromTail
# 印刷データの送信方式
  PrintPolicyOfProcessingPrintData
# モード9を使用するかどうか ( bool mode9_ )
  # Mode9
# 非圧縮モード ( bool raw_mode_ )
  # RawMode
# Collate印刷をするかどうか
  PrintCollate
# 印刷で文字の色違いをエラーにするかどうか
  PrintCheckMediaTextColor
# 印刷で背景の色違いをエラーにするかどうか
  PrintCheckMediaBackgroundColor
# マニュアルカットを待つか
  PrintCutPause